Exception on /save_image [POST]
Traceback (most recent call last):
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/ec2-user/segment-anything/start.py", line 133, in save_image
    img_bytes = base64.b64decode(imgData)
  File "/usr/lib64/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/ec2-user/segment-anything/start.py", line 133, in save_image
    img_bytes = base64.b64decode(imgData)
  File "/usr/lib64/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/ec2-user/segment-anything/venv/lib64/python3.9/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/ec2-user/segment-anything/start.py", line 133, in save_image
    img_bytes = base64.b64decode(imgData)
  File "/usr/lib64/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (654985) cannot be 1 more than a multiple of 4
<<<<<<< Updated upstream
[INFO] 2023-05-19 13:35:35,044 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 13:56:12,461 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 13:56:12,464 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-19 17:16:54,707 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 17:16:54,710 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
<<<<<<< Updated upstream
[INFO] 2023-05-20 01:41:26,070 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 01:41:26,080 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-20 02:02:21,836 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 02:02:21,839 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-20 02:04:28,322 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 02:04:28,325 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-20 02:11:54,014 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 02:11:54,016 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[ERROR] 2023-05-20 02:12:03,453 [app.py:1414, log_exception] Exception on /save_image [POST]
Traceback (most recent call last):
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Users/shinyzhang/work/segmentanything/start.py", line 144, in save_image
    await process_image('demo/src/assets/data/'+imgName, 'demo/src/assets/data/'+new_filename+'_embedding.npy')
  File "/Users/shinyzhang/work/segmentanything/create_npy.py", line 11, in process_image
    sam.to(device=device)
UnboundLocalError: local variable 'sam' referenced before assignment
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/shinyzhang/miniconda3/envs/segment/lib/python3.10/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Users/shinyzhang/work/segmentanything/start.py", line 144, in save_image
    await process_image('demo/src/assets/data/'+imgName, 'demo/src/assets/data/'+new_filename+'_embedding.npy')
  File "/Users/shinyzhang/work/segmentanything/create_npy.py", line 11, in process_image
    sam.to(device=device)
UnboundLocalError: local variable 'sam' referenced before assignment
[INFO] 2023-05-20 02:16:49,505 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 02:16:49,557 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[INFO] 2023-05-20 02:16:49,557 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-20 02:16:49,557 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:16:50,440 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:16:50,443 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:16:50,452 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:17:00,883 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:17:00] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:17:00] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:17:06,413 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:17:06] "OPTIONS /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:17:06] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:17:06,439 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:17:06] "[35m[1mPOST /save_image HTTP/1.1[0m" 500 -
127.0.0.1 - - [20/May/2023 02:17:06] "[35m[1mPOST /save_image HTTP/1.1[0m" 500 -
[INFO] 2023-05-20 02:19:07,152 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
[INFO] 2023-05-20 02:19:07,367 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:19:08,344 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:19:08,348 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:19:08,355 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:19:16,526 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
[INFO] 2023-05-20 02:19:16,731 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:19:17,673 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:19:17,676 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:19:17,683 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:19:53,480 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
[INFO] 2023-05-20 02:19:53,743 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:19:54,720 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:19:54,724 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:19:54,729 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:20:03,916 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
[INFO] 2023-05-20 02:20:04,137 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:20:05,083 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:20:05,087 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:20:05,094 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:20:06,116 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
[INFO] 2023-05-20 02:20:06,317 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:20:07,272 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:20:07,275 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:20:07,281 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:20:08,306 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
[INFO] 2023-05-20 02:20:08,505 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:20:09,481 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:20:09,486 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:20:09,492 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:20:16,521 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 02:20:16,531 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[INFO] 2023-05-20 02:20:16,531 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-20 02:20:16,531 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:20:17,430 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:20:17,433 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:20:17,440 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:20:22,244 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:20:22] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:20:22] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:20:27,882 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:20:27] "OPTIONS /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:20:27] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:20:27,906 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:20:27] "[35m[1mPOST /save_image HTTP/1.1[0m" 500 -
127.0.0.1 - - [20/May/2023 02:20:27] "[35m[1mPOST /save_image HTTP/1.1[0m" 500 -
[INFO] 2023-05-20 02:21:42,042 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
[INFO] 2023-05-20 02:21:42,258 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:21:43,147 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:21:43,151 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:21:43,158 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:22:00,545 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
[INFO] 2023-05-20 02:22:00,748 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:22:01,592 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:22:01,595 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:22:01,601 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:22:07,710 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
[INFO] 2023-05-20 02:22:07,934 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:22:08,848 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:22:08,852 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:22:08,858 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:22:12,942 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
[INFO] 2023-05-20 02:22:13,159 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:22:14,055 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:22:14,059 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:22:14,068 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:22:18,851 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 02:22:18,861 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[INFO] 2023-05-20 02:22:18,861 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-20 02:22:18,861 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:22:19,795 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:22:19,798 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:22:19,805 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:22:21,535 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:22:21] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:22:21] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:22:24,668 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:22:24] "OPTIONS /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:22:24] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:22:49,086 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:22:49] "[35m[1mPOST /save_image HTTP/1.1[0m" 500 -
127.0.0.1 - - [20/May/2023 02:22:49] "[35m[1mPOST /save_image HTTP/1.1[0m" 500 -
[INFO] 2023-05-20 02:23:48,500 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
[INFO] 2023-05-20 02:23:48,767 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:23:50,568 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:23:50,573 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:23:50,580 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:23:53,951 [start.py:31, <module>] begin service
begin service
[INFO] 2023-05-20 02:23:53,969 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[INFO] 2023-05-20 02:23:53,969 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-20 02:23:53,970 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:23:54,861 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:23:54,865 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:23:54,871 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:23:55,833 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:23:55] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:23:55] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:23:59,447 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:23:59] "OPTIONS /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:23:59] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:24:23,350 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:24:23] "POST /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:24:23] "POST /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:25:19,301 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
[INFO] 2023-05-20 02:25:19,537 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:25:20,537 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:25:20,542 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:25:20,549 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:25:48,179 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
[INFO] 2023-05-20 02:25:48,393 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:25:49,345 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:25:49,350 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:25:49,359 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:28:27,693 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
[INFO] 2023-05-20 02:28:27,897 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:28:28,834 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:28:28,837 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:28:28,843 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:28:35,555 [start.py:31, <module>] begin service
begin service
[INFO] 2023-05-20 02:28:35,565 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[INFO] 2023-05-20 02:28:35,565 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-20 02:28:35,565 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:28:36,461 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:28:36,465 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:28:36,471 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:28:46,244 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:28:46] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:28:46] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:28:49,020 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:28:49] "OPTIONS /delete HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:28:49] "OPTIONS /delete HTTP/1.1" 200 -
[INFO] 2023-05-20 02:28:49,029 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:28:49] "POST /delete HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:28:49] "POST /delete HTTP/1.1" 200 -
[INFO] 2023-05-20 02:28:49,037 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:28:49] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:28:49] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:28:49,886 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:28:49] "OPTIONS /delete HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:28:49] "OPTIONS /delete HTTP/1.1" 200 -
[INFO] 2023-05-20 02:28:49,898 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:28:49] "POST /delete HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:28:49] "POST /delete HTTP/1.1" 200 -
[INFO] 2023-05-20 02:28:49,906 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:28:49] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:28:49] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:28:53,862 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:28:53] "OPTIONS /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:28:53] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:29:19,399 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:29:19] "POST /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:29:19] "POST /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:29:38,533 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
[INFO] 2023-05-20 02:29:38,754 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:29:39,754 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:29:39,759 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:29:39,765 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:29:43,833 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
[INFO] 2023-05-20 02:29:44,063 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:29:45,087 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:29:45,091 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:29:45,097 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:29:59,412 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
[INFO] 2023-05-20 02:29:59,612 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:30:00,518 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:30:00,522 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:30:00,528 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:30:08,031 [start.py:31, <module>] begin service
begin service
[INFO] 2023-05-20 02:30:08,041 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[INFO] 2023-05-20 02:30:08,041 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-20 02:30:08,041 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:30:08,888 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:30:08,892 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:30:08,898 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:30:12,812 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:30:12] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:30:12] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:30:16,298 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:30:16] "OPTIONS /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:30:16] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:30:46,968 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:30:46] "POST /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:30:46] "POST /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:31:46,881 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
[INFO] 2023-05-20 02:31:47,115 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:31:48,358 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:31:48,363 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:31:48,370 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:31:52,470 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/create_npy.py', reloading
[INFO] 2023-05-20 02:31:52,667 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:31:53,670 [start.py:31, <module>] begin service
begin service
[WARNING] 2023-05-20 02:31:53,675 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:31:53,681 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:32:01,857 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
[INFO] 2023-05-20 02:32:02,086 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:32:02,980 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:32:02,985 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:32:02,992 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:32:09,115 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
[INFO] 2023-05-20 02:32:09,357 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:32:10,233 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:32:10,236 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:32:10,242 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:32:58,147 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/onnx.py', reloading
[INFO] 2023-05-20 02:32:58,356 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:32:59,272 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:32:59,276 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:32:59,282 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:33:25,810 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
[INFO] 2023-05-20 02:33:26,022 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:33:26,936 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:33:26,940 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:33:26,946 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:33:30,983 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 02:33:30,992 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[INFO] 2023-05-20 02:33:30,992 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-20 02:33:30,993 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:33:31,853 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:33:31,857 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:33:31,863 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:33:34,226 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:33:34] "GET /api/files HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:33:34] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-20 02:33:38,326 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:33:38] "OPTIONS /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:33:38] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:34:04,401 [_internal.py:186, _log] 127.0.0.1 - - [20/May/2023 02:34:04] "POST /save_image HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2023 02:34:04] "POST /save_image HTTP/1.1" 200 -
[INFO] 2023-05-20 02:35:25,915 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
[INFO] 2023-05-20 02:35:26,163 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:35:27,148 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:35:27,152 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:35:27,159 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:35:54,764 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/scripts/export_onnx_model.py', reloading
[INFO] 2023-05-20 02:35:54,981 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:35:55,902 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-20 02:35:55,906 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-20 02:35:55,912 [_internal.py:186, _log]  * Debugger PIN: 716-286-582
 * Debugger PIN: 716-286-582
[INFO] 2023-05-20 02:36:16,324 [_internal.py:186, _log]  * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
 * Detected change in '/Users/shinyzhang/work/segmentanything/start.py', reloading
[INFO] 2023-05-20 02:36:16,538 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-20 02:36:17,422 [start.py:30, <module>] begin service
begin service
=======
=======
[INFO] 2023-05-18 12:35:46,802 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-18 12:35:46,810 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-18 12:44:19,479 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-18 12:44:19,487 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-18 12:46:17,372 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-18 12:46:17,380 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[ERROR] 2023-05-19 03:28:21,716 [app.py:1414, log_exception] Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
[INFO] 2023-05-19 03:30:05,562 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 03:30:05,570 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[ERROR] 2023-05-19 03:30:44,288 [app.py:1414, log_exception] Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
[INFO] 2023-05-19 03:34:16,410 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 03:34:16,418 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[ERROR] 2023-05-19 03:37:07,860 [app.py:1414, log_exception] Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
[ERROR] 2023-05-19 03:37:28,194 [app.py:1414, log_exception] Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
[ERROR] 2023-05-19 03:38:36,952 [app.py:1414, log_exception] Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1553, in ensure_sync
    return self.async_to_sync(func)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1574, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
[INFO] 2023-05-19 03:42:36,675 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 03:42:36,685 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.4.226:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.4.226:5000
[INFO] 2023-05-19 03:42:36,685 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-19 03:42:36,686 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-19 03:42:38,202 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-19 03:42:38,209 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-19 03:42:38,210 [_internal.py:186, _log]  * Debugger PIN: 111-800-613
 * Debugger PIN: 111-800-613
[INFO] 2023-05-19 03:42:57,628 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:42:57] "GET /api/files HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:42:57] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-19 03:43:02,909 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:43:02] "OPTIONS /save_image HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:43:02] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-19 03:43:03,119 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:43:03] "[35m[1mPOST /save_image HTTP/1.1[0m" 500 -
172.30.1.254 - - [19/May/2023 03:43:03] "[35m[1mPOST /save_image HTTP/1.1[0m" 500 -
[INFO] 2023-05-19 03:43:04,083 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:43:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:43:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:43:04,163 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:43:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:43:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:43:04,173 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:43:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:43:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:43:34,085 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:43:34] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:43:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:43:34,166 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:43:34] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:43:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:43:34,176 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:43:34] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:43:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:44:04,088 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:44:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:44:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:44:04,170 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:44:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:44:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:44:04,179 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:44:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:44:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:44:21,946 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 03:44:21,954 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.4.226:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.4.226:5000
[INFO] 2023-05-19 03:44:21,954 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-19 03:44:21,955 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-19 03:44:23,471 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-19 03:44:23,478 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-19 03:44:23,478 [_internal.py:186, _log]  * Debugger PIN: 111-800-613
 * Debugger PIN: 111-800-613
[INFO] 2023-05-19 03:44:34,091 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:44:34] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:44:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:44:34,173 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:44:34] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:44:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:44:34,182 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:44:34] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:44:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:44:37,862 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:44:37] "GET /api/files HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:44:37] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-19 03:44:48,811 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:44:48] "OPTIONS /save_image HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:44:48] "OPTIONS /save_image HTTP/1.1" 200 -
[INFO] 2023-05-19 03:45:04,093 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:45:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:45:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:45:04,176 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:45:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:45:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:45:04,186 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:45:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:45:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:45:34,096 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:45:34] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:45:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:45:34,180 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:45:34] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:45:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:45:34,190 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:45:34] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:45:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:45:50,294 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:45:50] "POST /save_image HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:45:50] "POST /save_image HTTP/1.1" 200 -
[INFO] 2023-05-19 03:46:04,098 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:46:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:46:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:46:04,182 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:46:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:46:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:46:04,192 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:46:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:46:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:46:12,189 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:46:12] "GET /api/files HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:46:12] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-19 03:46:34,100 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:46:34] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:46:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:46:34,185 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:46:34] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:46:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:46:34,195 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:46:34] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:46:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:47:04,103 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:47:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:47:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:47:04,186 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:47:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:47:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:47:04,198 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:47:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:47:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:47:13,717 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:47:13] "GET /api/files HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:47:13] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-19 03:47:34,103 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:47:34] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:47:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:47:34,189 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:47:34] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:47:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:47:34,201 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:47:34] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:47:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:48:04,103 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:48:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:48:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:48:04,192 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:48:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:48:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:48:04,205 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:48:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:48:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:48:34,104 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:48:34] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:48:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:48:34,195 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:48:34] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:48:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:48:34,208 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:48:34] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:48:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:48:57,688 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:48:57] "GET /api/files HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:48:57] "GET /api/files HTTP/1.1" 200 -
[INFO] 2023-05-19 03:49:04,106 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:49:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:49:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:49:04,198 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:49:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:49:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:49:04,209 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:49:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:49:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:49:34,108 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:49:34] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:49:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:49:34,201 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:49:34] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:49:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:49:34,212 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:49:34] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:49:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:50:04,110 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:50:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:50:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:50:04,202 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:50:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:50:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:50:04,213 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:50:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:50:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:50:34,113 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:50:34] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:50:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:50:34,205 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:50:34] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:50:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:50:34,216 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:50:34] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:50:34] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:51:04,113 [_internal.py:186, _log] 172.30.0.114 - - [19/May/2023 03:51:04] "GET / HTTP/1.1" 200 -
172.30.0.114 - - [19/May/2023 03:51:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:51:04,208 [_internal.py:186, _log] 172.30.2.231 - - [19/May/2023 03:51:04] "GET / HTTP/1.1" 200 -
172.30.2.231 - - [19/May/2023 03:51:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:51:04,219 [_internal.py:186, _log] 172.30.1.254 - - [19/May/2023 03:51:04] "GET / HTTP/1.1" 200 -
172.30.1.254 - - [19/May/2023 03:51:04] "GET / HTTP/1.1" 200 -
[INFO] 2023-05-19 03:51:18,800 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 03:51:18,808 [_internal.py:186, _log] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.4.226:5000
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.4.226:5000
[INFO] 2023-05-19 03:51:18,808 [_internal.py:186, _log] [33mPress CTRL+C to quit[0m
[33mPress CTRL+C to quit[0m
[INFO] 2023-05-19 03:51:18,809 [_internal.py:186, _log]  * Restarting with stat
 * Restarting with stat
[INFO] 2023-05-19 03:51:20,328 [start.py:30, <module>] begin service
begin service
[WARNING] 2023-05-19 03:51:20,335 [_internal.py:186, _log]  * Debugger is active!
 * Debugger is active!
[INFO] 2023-05-19 03:51:20,335 [_internal.py:186, _log]  * Debugger PIN: 111-800-613
 * Debugger PIN: 111-800-613
[INFO] 2023-05-19 03:51:40,462 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 03:51:40,470 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-19 05:54:19,241 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 05:54:19,249 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[ERROR] 2023-05-19 08:38:24,993 [app.py:1414, log_exception] Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/opt/conda/envs/sam/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/conda/envs/sam/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/ec2-user/segmentanything/start.py", line 133, in save_image
    img_bytes = base64.b64decode(imgData)
  File "/opt/conda/envs/sam/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
Exception on /save_image [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/opt/conda/envs/sam/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/conda/envs/sam/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/conda/envs/sam/lib/python3.10/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/ec2-user/segmentanything/start.py", line 133, in save_image
    img_bytes = base64.b64decode(imgData)
  File "/opt/conda/envs/sam/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
>>>>>>> Stashed changes
[INFO] 2023-05-19 10:06:51,741 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 10:06:51,749 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-19 11:54:52,183 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-19 11:54:52,191 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
>>>>>>> Stashed changes
[INFO] 2023-05-20 02:57:24,963 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 02:57:24,971 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-20 03:43:58,370 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 03:43:58,378 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
[INFO] 2023-05-20 03:44:49,615 [start.py:30, <module>] begin service
begin service
[INFO] 2023-05-20 03:44:49,623 [wasyncore.py:486, log_info] Serving on http://0.0.0.0:5000
Serving on http://0.0.0.0:5000
